### ISSUE TITLE
Please tag the commits corresponding to releases

### ISSUE THREAD

**Issue by michel-slm** [JulienPalard/Pipe#10]
Just noticed this really elegant library from a mention on StackOverflow, and I wanted to browse around and see what the changes are between versions -- and noticed that the versions are not tagged!

Could you tag them, or in case you did but the tags didn't get pushed to GitHub, could you push them? Thanks!

**Comment by JulienPalard** [comment]
Done, thanks for reporting, and sorry for the lag (yup, more than 5 years).
