### ISSUE TITLE
documentation correction

### ISSUE THREAD

**Issue by hros** [JulienPalard/Pipe#102]
the docs state that
```python
[1, 2, [3]] | chain
```
Gives a TypeError: `chain argument #1 must support iteration` Consider using traverse.

However, the command does not give an error but rather returns a `<itertools.chain object>`
Only when casting to a `list`: 
```python
list([1, 2, [3]] | chain)
```
there is an error `TypeError: 'int' object is not iterable`

**Comment by JulienPalard** [comment]
Thanks for reporting, would you like to open a PR to fix it?

**Comment by hros** [comment]
created a PR

**Comment by JulienPalard** [comment]
Thanks!
