### ISSUE TITLE
Update package on pip

### ISSUE THREAD

**Issue by guilhermeleobas** [JulienPalard/Pipe#22]
Hi,

Can you update the pipe package on pip?

Just installed the package and these are the functions available:
`['Pipe', '__all__', '__author__', '__builtins__', '__credits__', '__date__', '__doc__', '__file__', '__name__', '__package__', '__version__', 'add', 'aggregate', 'all', 'any', 'as_dict', 'as_list', 'as_tuple', 'average', 'builtins', 'chain', 'chain_with', 'closing', 'concat', 'count', 'first', 'groupby', 'islice', 'itertools', 'izip', 'lineout', 'max', 'min', 'netcat', 'netwrite', 'permutations', 'reduce', 'reverse', 'select', 'skip', 'skip_while', 'socket', 'sort', 'stdout', 'sys', 'tail', 'take', 'take_while', 'tee', 'traverse', 'where']`

There are no *strip, lstrip, rstrip*

Regards

**Comment by JulienPalard** [comment]
Done.
