### ISSUE TITLE
unexpected indent

### ISSUE THREAD

**Issue by ramstein74** [JulienPalard/Pipe#25]
hello this
euler2 = fib() | where(lambda x: x % 2 == 0)
               | take_while(lambda x: x < 4000000)
               | add

gives me an error 
| take_while(lambda x: x < 4000000)
^
IndentationError: unexpected indent

can you help?

**Comment by JulienPalard** [comment]
Yes, I'll also update the readme, you can put parenthesis around the expression, like this:
from pipe import *

```
def fib():
    x, y = 1, 1
    yield 1
    while True:
        yield y
        x, y = y, x + y

euler2 = (fib() | where(lambda x: x % 2 == 0)
                | take_while(lambda x: x < 4000000)
                | add)
print(euler2)
```
