### ISSUE TITLE
passing parameters

### ISSUE THREAD

**Issue by ramstein74** [JulienPalard/Pipe#26]
hello, 
what if i want to pass paramenters between functions??
like 

[1,2,3] | func1(param1) |func2(param2)

the code should inject [1,2,3] in func1 adding the param1

Is this possible?
regards

**Comment by JulienPalard** [comment]
Yes it's how it works,`func1` will get `param1` as a parameter after the iterable:

```
>>> from pipe import Pipe
>>> @Pipe
... def func1(iterable, param1):
...     print(iterable, param1)
...     yield from iterable
... 
>>> @Pipe
... def func2(iterable, param2):
...     print(param2)
...     for i in iterable:
...         print(i)
... 
>>> [1, 2, 3] | func1("param1") | func2("param2")
param2
[1, 2, 3] param1
1
2
3
```

Don't be afraid of func2 being executed before func1, it happen because func1 is a generator here, so it waits for func2 to actually pull data before executing, it's a Python natural thing, not a Pipe thing.

**Comment by javadba** [comment]
How can those functions be defined?  I tried the following

@Pipe
def split(iterable, delim= ' '): 
    for s in iterable: yield s.split(delim)
        
@Pipe
def trim(iterable): 
    for s in iterable: yield s.strip()

But for the following: 

mylist = [1,2,3]      
mylist2 = mylist | split('\n') | trim | split(':') | as_list

the result is   

AttributeError: 'list' object has no attribute 'strip'
 (btw I realized you already have a strip command .. but i'd love to be able to define my own functions)

**Comment by javadba** [comment]
I tried *your* code above and the result is: *invalid syntax* on the `yield from`:

from pipe import Pipe
@Pipe
def func1(iterable, param1):
  print(iterable, param1)
  yield from iterable
@Pipe
def func2(iterable, param2):
  print(param2)
  for i in iterable:
    print(i)
[1, 2, 3] | func1("param1") | func2("param2")
  File "<ipython-input-2-6f71469d1f2e>", line 5
    yield from iterable
             ^
SyntaxError: invalid syntax

**Comment by PuneethaPai** [comment]
Why is this still open issue. Can we close this?
Would be happy to contribute if there are any ideas to add. Great work @JulienPalard

**Comment by JulienPalard** [comment]
I think we can close this :) Thanks @PuneethaPai
