### ISSUE TITLE
Shadowing built-in functions

### ISSUE THREAD

**Issue by nykh** [JulienPalard/Pipe#30]
These four functions in the package 

- any()
- all()
- max()
- min()

shadow built-in functions. Since python doesn't have an easy way to hide certain names during `from pipe import *`, may I suggest renaming name (perhaps simply prefix them with `p` like `pmax`?) Since we already took the stance of renaming `map` to `select` and `filter` to `where` I think this is in keeping with the whole strategy and will allow users to `from pipe import *` without worrying about shadowing.

Since this is definitely a breaking change, I respect your opinion. The exact naming is also up to you.

**Comment by JulienPalard** [comment]
This is typically why one should  never use `import *` outside an REPL.

**Comment by JulienPalard** [comment]
Hi @nykh!

I resolved this issue by deprecating all function that were "leaf" functions (see README), which in fact removed max, min, any and all (any many others *useless* functions).

I keep the function with a deprecation warning until like 2021, you'll be able to "from pipe import *", which is still a bad idea I think :)
