### ISSUE TITLE
Is there any possibility to add more functions?

### ISSUE THREAD

**Issue by sergiors** [JulienPalard/Pipe#38]
I've been working on a library called [pyf](https://github.com/sergiors/pyf) that implements other functions that don't exist in **JulienPalard/Pipe**

I'd like to know, Is there plans to add more functions?
If don't, I'd like to know the reason.

**Comment by JulienPalard** [comment]
If you find a few really usefull and think they deserve to be in Pipe, I could accept a PR to add them.

Else, you can also see your project as a "testbed for future Pipe functions" and I'll gladly accept a PR linking to pyf from my README. Some PR has already been refused, demed "not usefull enough", you could copy them to pyf to further expand the supported functions.
