### ISSUE TITLE
How to apply function to each element?

### ISSUE THREAD

**Issue by heckad** [JulienPalard/Pipe#42]
I want to convert elements to int. It's like `map(int, [1,2,3])`. How to do it?

**Comment by JulienPalard** [comment]
We're using the name `select` for this:

```
>>> "123" | select(int) | add
6
```

I choose `select` for its similarity with SQL select, and I were having a where:

```
>>> range(10) | where(lambda x: x % 2 == 0) | select(lambda x: x ** 2) | concat
'0, 4, 16, 36, 64'
```

being the equivalent of:

```
>>> [x ** 2 for x in range(10) if x % 2 == 0]
[0, 4, 16, 36, 64]
```
