### ISSUE TITLE
Could the built-in functions always output an iterator?

### ISSUE THREAD

**Issue by ddebernardy** [JulienPalard/Pipe#43]
When the input is an iterator, it's quite tempting to run `next()` on the output. But a number of the functions don't return an iterator, resulting in a `TypeError`. e.g.:

```python
>>> next(range(10) | tail(2))
[...]
TypeError: 'collections.deque' object is not an iterator
```

It would be sweet if all/most of the functions would return an actual iterator. Exceptions would of course be things like `as_list` where you're explicitly asking for an output type.

My use-case, in case it matters, is leisurely throwing python scripts at a csv file that doesn't fit in memory. Pandas tries to load the whole thing in memory and fails, unless I use the chunksize argument, which makes it choke every so often -- and the syntax is god awful. Line by line seems to work fine, however slow. I ran into your library while looking for one that could basically support some kind of read_csv | some_stuff | more_stuff | write_csv type of workflow and do the entire thing row by row without me needing to reinvent the wheel. (Suggestions welcome if you know of a better option.)

**Comment by JulienPalard** [comment]
It make sense, PR are welcome :)

**Comment by ddebernardy** [comment]
Yeah, but upon reflection it'll likely break the scripts of existing users. Any user who currently expects tail to return a `deque` will be ripping their hair out. Forking the lib will likely be a saner approach.

**Comment by JulienPalard** [comment]
Or just redefine tail as a pipe in your code instead of importing it, like this:

```
from pipe import Pipe
@Pipe
def tail(iterable, qty):
    for item in deque(iterable, maxlen=qte):
        yield item
```

**Comment by ddebernardy** [comment]
More like:

```
yield from deque(iterable, maxlen=qte)
```

But yeah, that's kind of what I'm getting at.

Aside: any odds you might have any idea of how to make this work?

pipeline = (
    foo
    | bar
    | baz
)

def process(pipeline, *args):
    [...]
    records = records | pipeline
    yield from records

**Comment by ddebernardy** [comment]
Nm, found it. If you add the following method to Pipe, you can have standalone pipes:

```python```
    def __or__(self, other):
        if isinstance(other, Pipe):
            return Pipe(lambda x: other.function(self.function(x)))
```

You can then do:

data = [3, 2, 1]

pipeline = (
    foo
    | bar
    | baz
)

for datum in data:
    print(datum)

for piped_datum in data | pipeline:
   print(piped_datum)
```

**Comment by ddebernardy** [comment]
Oh, and this might have slightly better performance than using a lambda:

```python
    def __call__(self, *args, **kwargs):
        return Pipe(partial(self.function, *args, **kwargs))
```
