### ISSUE TITLE
Configurable Pipeline with List of transformations

### ISSUE THREAD

**Issue by PuneethaPai** [JulienPalard/Pipe#45]
**[Feature Request]**
Hi @JulienPalard ,
I have an idea wanna run by you before I raise Pull request.
I wanna add capability where user can define various transformations with `@Pipe` and then have these transformations as part of a configurable pipeline. This pipeline can be reused multiple time rather than defining the same set of transformations to be applied on input every time.

Idea is:

```
class Pipeline:
    def __init__(self, methods):
        self.methods = methods

    def execute(self, value):
        return self.__recursive(value, self.methods)

    def __recursive(self, value, methods):
        if methods:
            return self.__recursive(value | methods[0], methods[1:])
        return value


if __name__ == '__main__':
    methods = [
        select(lambda x: x * x),
        where(lambda x: x % 2 == 1),
        collect
    ]
    pipeline = Pipeline(methods=methods)
    assert [1, 9, 25, 49, 81] == pipeline.execute(range(10))
```

Let me know what you think.
Thanks

**Comment by JulienPalard** [comment]
Why not using a Python function?

```python
def pipeline(x):
    return (x | select(lambda x: x * x) |
            where(lambda x: x % 2 == 1) |
            as_list)

assert [1, 9, 25, 49, 81] == pipeline(range(10))
```

**Comment by PuneethaPai** [comment]
Hi @JulienPalard 

Thanks replying. Presently I am following the same functional way of doing Pipeline. Both our approach is of achieving the same thing in different ways.

My Way: 
It is like different objects for different Pipeline. The logic of chaining multiple transformation is written only once in the class and will be reused by all the objects.

Your Way:
Every time we may need to repeat/write the same chaining logic every time for different pipeline with different Pipeline function names.

Also one more idea I had to combine both our approaches.
```
def pipeline(methods):
    def execute(value):
        return __recursive(value, methods)

    def __recursive(value, methods):
        if methods:
            return __recursive(value | methods[0], methods[1:])
        return value

    return execute


if __name__ == '__main__':
    methods = [
        select(lambda x: x * x),
        where(lambda x: x % 2 == 1),
        collect
    ]
    execute = pipeline(methods)
    assert [1, 9, 25, 49, 81] == execute(range(10))
```

Let me know what you think.

Thanks

**Comment by JulienPalard** [comment]
>  Every time we may need to repeat/write the same chaining logic every time for different pipeline with different Pipeline function names.

Do you mean that:
```
    methods = [
        select(lambda x: x * x),
        where(lambda x: x % 2 == 1),
        collect
    ]
    execute = pipeline(methods)
    assert [1, 9, 25, 49, 81] == execute(range(10))
```

Is shorter than
```
def pipeline(x):
    return (x | 
            select(lambda x: x * x) |
            where(lambda x: x % 2 == 1) |
            as_list)

assert [1, 9, 25, 49, 81] == pipeline(range(10))
```

?

**Comment by PuneethaPai** [comment]
Sorry I see what you meant.
I was using list and iterating to chain the outputs and functions.
But inplace of list I could have chained them as you showed in the first place to avoid chaining later.
So that concludes it and I think this [Feature Request] was redundant and can be closed.
Thanks
