### ISSUE TITLE
PEP

### ISSUE THREAD

**Issue by mjmdavis** [JulienPalard/Pipe#47]
Have you considered making a [PEP](https://www.python.org/dev/peps/) for this? Is there one and I missed it?

**Comment by JulienPalard** [comment]
IIRC I once spoke about this lib on python-ideas and it did not received that good reactions.

I'm not a big fan myself of pushing operator overloading that far: it's a bug magnet. And I don't see how it can be enhanced. So I prefer keeping it out of the stdib.

I'm also not a huge fan of having some "pipe" return values and some other returning generators, that's probably not that hard to fix by deprecating "leaf pipes", like deprecating `pipe.add` (better used as `sum(the|pipe|expression)`).
