### ISSUE TITLE
How do you handle types that implement | ?

### ISSUE THREAD

**Issue by vsraptor** [JulienPalard/Pipe#50]
if variable X of type Y implement |-operator the pipe is not working because the left var has precedence in interpretation ... how do you overcome that case ? Ex.:

      X | ZZ

    TypeError: bitarray object expected for bitwise operation

**Comment by JulienPalard** [comment]
That's the very limit of `Pipe`, there's no clean way to overcome this...

I think we should write a warning in the README, if you have a good example to put in the warning, a PR would be appreciated :)

**Comment by vsraptor** [comment]
May be if you can provide a way to pass the symbol as parameter , if possible !!
What I did was to change from __ror__ to __lt__

here is an example : 

In [2]: b = bitarray('10110')

In [3]: p = Pipe(lambda x : x * 2 )

In [4]: b | p
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-31435fed5083> in <module>()
----> 1 b | p

TypeError: bitarray object expected for bitwise operation

In [5]: b * 2
Out[5]: bitarray('1011010110')

**Comment by JulienPalard** [comment]
Using non-reverse operators would work only if we return an iterable that has it, so only for the "non first" step of the pipe sequence, which is just a bug magnet.
