### ISSUE TITLE
Using Pipes in the functions

### ISSUE THREAD

**Issue by vsraptor** [JulienPalard/Pipe#56]
i'm stuck on something that seem it should be simple.. 

```
@Pipe
def flat(it): return sum(it,[])

syns = map(lambda z : z.synsets())
```

what I want instead is : 

`syns = map(lambda z : z.synsets()) | flat`

so I can say : 

`.... | syns`

instead of : 

`... | syns | flat`

**Comment by JulienPalard** [comment]
> syns = map(lambda z : z.synsets()) | flat

If I understand correctly you're trying to combine two Pipe functions to create a new one.

I don't have a syntax for this, but it should be as easy as:

```python
@Pipe
def combine(iterable, left, right):
    return iterable | left | right
```

and use it as:
```
syns = combine(map(lambda z: z.synsets(), flat)
```

While I'm here, your `flat` pipe looks like my `chain` pipe?

**Comment by vsraptor** [comment]
yep i use chain .. just playing with different variants.. thanks
