### ISSUE TITLE
two iterators as args

### ISSUE THREAD

**Issue by vsraptor** [JulienPalard/Pipe#57]
is this correct way of doing it ..

```

@Pipe
def prod(it): 
	for x in itertools.product(it[0],it[1]): yield x

```
i use it like this : 

`
(it,it) | prod`

**Comment by vsraptor** [comment]
Also is there operation that can interleave n-iterable like this : 

`it1 | it2 | it3 | ... | itn | blah => [ [it1[0],it1[0],..,itn[0]], [it1[1],it1[1],..,itn[1]] ..... [it1[n],it1[n],..,itn[n]] ] `

**Comment by JulienPalard** [comment]
> ```
> @Pipe
> def prod(it): 
> 	for x in itertools.product(it[0],it[1]): yield x
> ```

At first glance I'm not fan of it, it almost breaks the following statement: `all pipes take an iterable and give an iterable`, which is nice to keep (no surprises).

Maybe go for a generic one:

```
@Pipe
def prod(it):
    for x in itertools.product(*it):
        yield x
```

which allows for:

```
print(list(([1, 2], [3, 4], [5, 6]) | prod))
```

Next for your:
```text
it1 | it2 | it3 | ... | itn | blah => [ [it1[0],it1[0],..,itn[0]], [it1[1],it1[1],..,itn[1]] ..... [it1[n],it1[n],..,itn[n]] ] 
```
this is simply the [builtin zip](https://docs.python.org/3/library/functions.html#zip) function:

    zip(it1, it2, it3, ... itn)

when you write `it1 | it2 | i3` it looks like you're mixing iterables and pipes. See iterables as water and pipes as pipes, you can write:

    ["wa", "ter"] | prod | chain

meaning you send some water to the `prod` pipe and the `chain` pipe, and you get somethng at the end of it:

    print(list(["wa", "ter"] | prod | chain))
    ['w', 't', 'w', 'e', 'w', 'r', 'a', 't', 'a', 'e', 'a', 'r']

But you can't "pipe" water thrue water (you can't send iterable "to iterables"):

    ["wa", "ter"] | ["wat", "er"]  # does not make sense

**Comment by vsraptor** [comment]
that was detailed ..thanks 
Pipes were very helpful with exploring WordNet, cause there is alot of List-of-List operations

https://gist.github.com/vsraptor/8815944d1e75947ad0c3676c0279519a

i think I will refactor my file parsing... to pipes
