### ISSUE TITLE
Lambda replacements

### ISSUE THREAD

**Issue by gamis** [JulienPalard/Pipe#60]
Hi!

I like this package! I wrote something similar: https://github.com/gamis/flo, but I think I like yours better.

The one thing mine has that yours doesn't is a concise replacement for lambda functions. I find `lambda x: x**2` kind of annoying. With my library, instead of having code that looks like
```python
mylist = ['pretty','cool','items', 'kiddo']
myindex = mylist | map(lambda x: x.upper()) | where(lambda x: 'E' in x) | groupby(key=lambda x: x[0]) | select(lambda x: x[0])
```

it could look like 
```python
myindex = mylist | map( _.upper() ) | where( _.has('E') ) | groupby( _[0] ) | select( _[0] )
```
or potentially even terser:

```python
myindex = mylist | map_.upper() | where_.has('E') | groupby_[0] | select_[0]
```

If you're interested in such an addition, I can work on a PR in the next month or two. In any case, I'd love any feedback you have.

Thanks!

Greg

**Comment by JulienPalard** [comment]
First impression: If `_.has('E')` generates a lambda like `lambda x: 'E' in x`, it could be packaged as its own, and used in conjunction with `Pipe`, but also many other contexts, would'nt this be better?

I would avoid using `_`, it's already used by unused variables, gettext, and match wildcard, that's already too much.

I would name it `it`.

Like:

```python
it.has("E")
```

What do you think?

**Comment by gamis** [comment]
Thanks for the fast reply!

Yes, it could be a separate package but I think it would make Pipe more compelling to have it included. Maybe the two packages could at least reference each other in their documentation.

As for the underscore notation, yes, i agree completely. In practice I use e_, short for “each” but the package lets you use whatever you want. I often use “it” to mean “iterator”.

—-
Sent from my phone
________________________________

**Comment by JulienPalard** [comment]
Yes, cross-linking the docs with some examples make sense, but I don't think people using `it` should have to pull `Pipe` nor the other way around.

**Comment by JulienPalard** [comment]
I'm closing the issue, feel free to open a PR if you're maintaining your project and would like a back-reference from pipe's README to you project.
