### ISSUE TITLE
add "how to install" to readmy

### ISSUE THREAD

**Issue by roschly** [JulienPalard/Pipe#61]
Add a how to install in the introduction of the readme, e.g.:
`pip install pipe`

Minor issue, but one can't assume it's simply called pipe at PYPI.

**Comment by JulienPalard** [comment]
Would you like to author a PR to fix this? I'll gladly merge it :)

**Comment by devRMA** [comment]
> Would you like to author a PR to fix this? I'll gladly merge it :)

#66 :)

**Comment by JulienPalard** [comment]
Done by #66.
