### ISSUE TITLE
How about "apply" instead of "select"

### ISSUE THREAD

**Issue by swehba** [JulienPalard/Pipe#62]
Absolutely brilliant library. Thank you for it. Now that I have it as my shiny new hammer I'm looking for a rusty nail to use it on. One minor suggestion — did you consider other names for "select". As it is, "select" sounds like it should filter, not operate like map (which I see is also supported). Might "apply" be a better term?

**Comment by JulienPalard** [comment]
Thanks for the compliment and taking the time to write an issue.

`map` is an alias for `select`, I do expose both so one can pick them depending on their intention, example:

```pycon
>>> users = [{"username": "mdk", "firstname": "julien"}, {"username": "lisa", "firstname": "lisa"}]
>>> users | select(lambda user: user["firstname"]) | map(str.capitalize))
['Julien', 'Lisa']
```

Here when I use `map` I mean "apply this function to all elements", and when I use `select` I mean "take this". The effect is the same, the intention is different.

Also in real world usage of `Pipe` (I'm not aware of any but I bet there's) I don't think people are using a lot those "example" implementations, and are doing their own specific ones, so they probably just import the `Pipe` decorator and don't really care about "example" wordings.

**Comment by jerabaul29** [comment]
Agree on a beautiful library, many thanks :) .

I actually +1 on the initial comment, the name "select" was quite confusing for me, and "apply" would be nice to have, as this way one can just:

```
from pipe import apply
```

to use it *without* overriding the builtin ```map``` function (to be honest, I thought that the only reason to have an alias for ```pipe.map``` into something else was so that the alias can be easily imported without overriding map and surprise the user :) ).

**Comment by JulienPalard** [comment]
What about:

```python
from pipe import map as apply
```

if you really feed it's more readable as `apply`?

It may (or may not) change my mind about accepting apply if one can provide a good example of it being more semantically correct (thus more readable) than `map`.

**Comment by swehba** [comment]
Ha ha. I am not going to try very hard to change your mind. I can definitely live with "select". Cheers.
