### ISSUE TITLE
Add a LICENSE to repository and PyPI package

### ISSUE THREAD

**Issue by sugatoray** [JulienPalard/Pipe#63]
Please add a license file to the repository and the PyPI package as well.

The PyPI package says: `MIT` license, but does not include a LICENSE file in the `tar.gz` file.

**Comment by sugatoray** [comment]
cc: @JulienPalard

**Comment by sugatoray** [comment]
I am working on adding `pipe` on conda-forge channel, so it could be installed using conda as well. The license file is a necessity. https://github.com/conda-forge/staged-recipes/pull/17245

**Comment by JulienPalard** [comment]
I fixed the classifiers in setup.py (should update on pypi.org on the next release)
