### ISSUE TITLE
about lazy iteration

### ISSUE THREAD

**Issue by jerabaul29** [JulienPalard/Pipe#68]
Just a small question to clarify: I looked at the code, and this library is not lazily executed, right? May be a good idea to add a small note in the readme that this library is providing "syntactic sugar" but no "expected" / advanced functional programming goodies like lazy evaluation (which some people coming from other languages may expect quite strongly when they see some piping like, functional programming like syntax :) ).

Just to be clear, I love this library, and this is not a criticism, just I think it would be great to make it clear to the user - and also, that may be inspiration for future authors / future improvements etc :) .

**Comment by JulienPalard** [comment]
I don't think we can say it is or it is not lazy evaluated, it's only syntaxic sugar. Feed it a generator and it's lazy, feed it a list and it's not, see:


```pycon
>>> from pipe import *
>>> def verbose_generator():
...     while True:
...         print("tac")
...         yield 1
... 
>>> verbose_generator() | where(lambda x: x % 2 == 0) | select(lambda x: x ** 2)
<map object at 0x7f76ae5433c0>
```

It it were not lazy, it would have entered an infinite loop of `print("tac")`.

**Comment by jerabaul29** [comment]
Ok, thanks. Wonder if this may deserve to be explained a bit in the readme :) .

**Comment by JulienPalard** [comment]
I don't know, if you find a nice way to word this in a way it would have answered your question clearly, feel free to open a PR :)

**Comment by jerabaul29** [comment]
Sorry for the delay... I finally had the time to look a bit at this, and it actually looks really good. (i) For me lazily evaluated would rather mean that only the needed terms of the "first element in the chain" are generated when they are needed, and this is the case, (ii) seems to work with list too. Or am I missing something?

```python
from pipe import *

from icecream import ic

ic.configureOutput(prefix="", outputFunction=print)


def dummy_func(x):
    print(f"processing at value {x}")
    return x


print("----- test using a range() as input -----")


res_with_range = (range(100) | select(dummy_func)
                             | where(lambda x: x % 2 == 0)
                             | take(2))

print("*** what is the resulting object ***")
ic(res_with_range)

print("*** what happens when we force evaluation ***")
ic(list(res_with_range))

"""
This prints:

----- test using a range() as input -----
*** what is the resulting object ***
res_with_range: <generator object take at 0x7f60bd506d60>
*** what happens when we force evaluation ***
processing at value 0
processing at value 1
processing at value 2
processing at value 3
processing at value 4
list(res_with_range): [0, 2]
"""

print("----- test using a list as input -----")

list_to_100 = list(range(100))
ic(type(list_to_100))
ic(len(list_to_100))

res_with_list = (list_to_100 | select(dummy_func)
                             | where(lambda x: x % 2 == 0)
                             | take(2))

print("*** what is the resulting object ***")
ic(res_with_list)

print("*** what happens when we force evaluation ***")
ic(list(res_with_list))

"""
This prints:

----- test using a range() as input -----
*** what is the resulting object ***
res_with_range: <generator object take at 0x7fa1933a6d60>
*** what happens when we force evaluation ***
processing at value 0
processing at value 1
processing at value 2
processing at value 3
processing at value 4
list(res_with_range): [0, 2]
----- test using a list as input -----
type(list_to_100): <class 'list'>
len(list_to_100): 100
*** what is the resulting object ***
res_with_list: <generator object take at 0x7fa193308cf0>
*** what happens when we force evaluation ***
processing at value 0
processing at value 1
processing at value 2
processing at value 3
processing at value 4
list(res_with_list): [0, 2]
"""
```

So that looks really great. I can try to push a small example to the readme.

**Comment by jerabaul29** [comment]
This is clear to me now, feel free to close together with the pull request :) .

**Comment by jerabaul29** [comment]
Merged, closing.
