### ISSUE TITLE
pylint issue

### ISSUE THREAD

**Issue by ckn12345** [JulienPalard/Pipe#70]
The code snipped from the readme produces an pylint error:

```python
sum(range(100) | where(lambda x: x % 2 == 0))
```

`No value for argument 'predicate' in function call pylint(no-value-for-parameter)`

**Comment by JulienPalard** [comment]
Hi!

Thanks for reporting!!

I don't think pylint understands that `where` is not a function that takes two arguments but a `Pipe` instance, due to the presence of a decorator replacing it.

Issue should be opened pylint side with a simple reproducer, maybe like:

```python
def partializer(const):
    def decorator(fct):
        def decorated(*args, **kwargs):
            return fct(const, *args, **kwargs)
        return decorated
    return decorator


@partializer(5)
def add_five(a, b):
    return a + b


print(add_five(5))
```

**Comment by ckn12345** [comment]
Hi Julian,

Thanks for the quick reply. Will report this to the pylint team. 

Thank you for your awesome library makes my code look so much cleaner and easier to read.

Best regard

Christian
