### ISSUE TITLE
IDEA: fan out operator

### ISSUE THREAD

**Issue by gdamjan** [JulienPalard/Pipe#8]
You could implement the & (or + ?) operator as a fan out operator.
It could be used if you want to send the output of one Pipe to several others at the same time, something like:

```
[1,2,3,4] | where(...) | ( stdout & sum & max )
```

Of course the result is a bit questionable... a pipeable tuple ?

**Comment by JulienPalard** [comment]
Anyway, I won't patch the __ror__ of tuples to implement this.
