### ISSUE TITLE
Typo on PyPI page

### ISSUE THREAD

**Issue by brendalf** [JulienPalard/Pipe#84]
There is a typo on the PyPI page.
It should be "enabling". 

![image](https://user-images.githubusercontent.com/10671410/202221537-799cf980-4848-464e-9f45-69da58883138.png)

**Comment by JulienPalard** [comment]
Thanks for telling!

I fixed it project side, but to reflect the change pypi side I'll have to do a release. I probably won't release just for this typo so it'll take some time to reflect on PyPI.
